version: '3.8'

services:
  postgresql_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    # By using a named volume the PostgreSQL data is persisted across container restarts and upgrades.
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_web_app
    ports:
      - "5000:5000"
    depends_on:
      postgresql_db:
        condition: service_healthy
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@postgresql_db:5432/postgres
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

volumes:
  pgdata:
